# 파이토치 패키지 기본 구성

**torch**

메인 네임스페이스. 텐서 등의 다양한 수학 함수가 포함되어있으며 Numpy와 유사한 구조 가진다.

**torch.autograd**

자동 미분을 위한 함수들이 포함되어 있다. 자동 미분의 on/off를 제어하는 콘텍스트 매니저(enable_grad/no_grad)나 자체 미분 가능 함수를 정의할 때 사용하는 기반 클래스인 'Function'등이 포함되어 있다.

**torch.nn**

신경망을 구축하기 위한 다양한 데이터 구조나 레이어 등이 정의되어 있다. 예를 들어 RNN, LSTM과 같은 레이어, ReLU와 같은 활성화 함수, MSELoss와 같은 손실함수 등이 있다.

**torch.optim**

SGD를 중심으로 한 파라미터 최적화 알고리즘이 구현되어 있다.

**torch.utils.data**

SGD의 반복 연산을 실행할 때 사용하는 미니배치용 유틸리티 함수가 포함되어 있다.

**torch.onnx** 

ONNX(Open Neural Network Exchange)의 포맷으로 모델을 export할 때 사용한다. 서로 다른 딥러닝 프레임워크간에 모델을 공유할 때 사용하는 포맷이다.

# PyTorch Tensor Shape Convention

**2D Tensor**
- |t| = (Batch size, dim)

**3D Tensor**
- |t| = (Batch_size, width, height)

**3D Tensor(NLP)**
- |t| = (Batch_size, length, dim)


**NLP 분야의 3D 텐서 예시**

In [3]:
data = [['나는 사과를 좋아해'], ['나는 바나나를 좋아해'], ['나는 사과를 싫어해'], ['나는 바나나를 싫어해']]

컴퓨터가 이해할 수 있도록 문장을 단어별로 나눠줘야 한다.

In [12]:
for i in range(len(data)) : 
    sentence = list(data[i][0].split(' '))
    data[i] = sentence

In [13]:
data

[['나는', '사과를', '좋아해'],
 ['나는', '바나나를', '좋아해'],
 ['나는', '사과를', '싫어해'],
 ['나는', '바나나를', '싫어해']]

In [9]:
list(data[0][0].split(' '))

['나는', '사과를', '좋아해']

단어를 3차원의 벡터로 변환했다고 가정

'나는' = [0.1, 0.2, 0.9]\
'사과를' = [0.3, 0.5, 0.1]\
'바나나를' = [0.3, 0.5, 0.2]\
'좋아해' = [0.7, 0.6, 0.5]\
'싫어해' = [0.5, 0.6, 0.7]

In [14]:
data = [[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
        [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]],
        [[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.5, 0.6, 0.7]],
        [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.5, 0.6, 0.7]]]

(4 $\times$ 3 $\times$ 2)의 크기를 가지는 3D 텐서가 된다.

batch size를 2로 하면 ,


첫번째 배치 #1

[[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],\
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]]]

두번째 배치 #2

[[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.5, 0.6, 0.7]],\
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.5, 0.6, 0.7]]]

## 파이토치 텐서 선언하기

In [19]:
import torch

In [20]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [21]:
print(t.dim())  # rank. 즉, 차원
print(t.shape)  # shape
print(t.size()) # shape


1
torch.Size([7])
torch.Size([7])


In [18]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # 인덱스를 통한 원소 접근

t[0] t[1] t[-1] =  0.0 1.0 6.0


In [22]:
print(t[0], t[1], t[-1])  # 인덱스로 접근
print(t[2:5], t[4:-1])    # 슬라이싱
print(t[:2], t[3:])       # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [24]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


## 브로드캐스팅
텐서의 크기가 맞지 않을 때 자동으로 크기를 맞춰서 계산 

In [27]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1+m2)

tensor([[5., 5.]])


벡터+스칼라

In [28]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])
